# Generated by Django 2.2.7 on 2019-11-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_userprofileinfo_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='nickname',
        ),
    ]
