# Generated by Django 2.2.7 on 2019-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_remove_userprofileinfo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='nickname',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
    ]
