# Generated by Django 2.2.7 on 2019-11-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0006_auto_20191106_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics'),
        ),
    ]
