# Generated by Django 2.2.7 on 2019-11-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0007_auto_20191107_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groups', models.CharField(max_length=18)),
                ('Description', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Tag', models.CharField(max_length=15)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donor', to=settings.AUTH_USER_MODEL)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
