# Generated by Django 2.2.7 on 2019-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20191114_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
