# Generated by Django 2.2.7 on 2019-11-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0011_auto_20191115_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friendof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friendof', to=settings.AUTH_USER_MODEL)),
                ('Friendslist', models.ManyToManyField(related_name='Friendslist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
