# Generated by Django 2.2.7 on 2019-11-15 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0012_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='Friendof',
        ),
        migrations.AddField(
            model_name='friends',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='Friendslist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
