# Generated by Django 2.2.7 on 2019-11-22 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0013_auto_20191115_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftoftransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('Damount', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=18)),
                ('Time1', models.DateTimeField(auto_now=True)),
                ('Time2', models.DateTimeField(auto_now=True)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donor1', to=settings.AUTH_USER_MODEL)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
