# Generated by Django 2.2.7 on 2019-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0014_ftoftransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftoftransaction',
            name='Time1',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
