# Generated by Django 2.2.7 on 2019-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0014_ftoftransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftoftransaction',
            name='Tag',
            field=models.CharField(default='Others', max_length=15),
        ),
        migrations.AlterField(
            model_name='ftoftransaction',
            name='Time1',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
