# Generated by Django 2.2.7 on 2019-11-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0016_auto_20191123_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='Group',
            new_name='Group_name',
        ),
    ]
