# Generated by Django 2.2.7 on 2019-11-23 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0016_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifications',
            new_name='notificationsModel',
        ),
    ]
