# Generated by Django 2.2.7 on 2019-11-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0017_auto_20191123_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftoftransaction',
            name='Date',
            field=models.CharField(default='24/11/2019', max_length=25),
        ),
        migrations.AddField(
            model_name='ftoftransaction',
            name='Expenditure',
            field=models.IntegerField(default=0),
        ),
    ]
