# Generated by Django 2.2.7 on 2019-11-23 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dappx', '0018_auto_20191123_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='GroupsModel',
        ),
    ]
