# Generated by Django 2.2.7 on 2019-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0018_auto_20191124_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftoftransaction',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='ftoftransaction',
            name='Expenditure',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date2',
            field=models.CharField(default='24/11/2019', max_length=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Expenditure',
            field=models.IntegerField(default=0),
        ),
    ]
