# Generated by Django 2.2.7 on 2019-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0019_auto_20191123_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftoftransaction',
            name='Tag',
            field=models.CharField(default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='Tag',
            field=models.CharField(default='other', max_length=15),
        ),
    ]
