# Generated by Django 2.2.7 on 2019-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0019_auto_20191124_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftoftransaction',
            name='Date2',
            field=models.CharField(default='2019-11-24', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date2',
            field=models.CharField(default='2019-11-24', max_length=25),
        ),
    ]
