# Generated by Django 2.2.7 on 2019-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0024_auto_20191125_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ftoftransaction',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ftoftransaction',
            name='Damount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='Damount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
